// <auto-generated />
using System;
using Assignment1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment1.Migrations
{
    [DbContext(typeof(IncidentContext))]
    [Migration("20210220215731_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment1.Models.Customer", b =>
                {
                    b.Property<int>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("customerCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerFullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            customerId = 1,
                            customerCity = "San Francisco",
                            customerEmail = "Kanthoni@pge.com",
                            customerFullName = "Kaitlyn Anthoni"
                        },
                        new
                        {
                            customerId = 2,
                            customerCity = "Washington",
                            customerEmail = "ania@pmma.nidc.com",
                            customerFullName = "Ana Irvin"
                        },
                        new
                        {
                            customerId = 3,
                            customerCity = "Mission Viejo",
                            customerEmail = " ",
                            customerFullName = "Gonzalo Keeton"
                        },
                        new
                        {
                            customerId = 4,
                            customerCity = "Sacramento",
                            customerEmail = "amauro@yahoo.org",
                            customerFullName = "Anton Mauro"
                        },
                        new
                        {
                            customerId = 5,
                            customerCity = "Fresco",
                            customerEmail = "Kmayte@fresco.ca.gov",
                            customerFullName = "Kendall Mayte"
                        },
                        new
                        {
                            customerId = 6,
                            customerCity = "Los Angeles",
                            customerEmail = "kenzie@mma.jobtrak.com",
                            customerFullName = "Kenzie Quinn"
                        },
                        new
                        {
                            customerId = 7,
                            customerCity = "Fresno",
                            customerEmail = "marvin@expedata.com",
                            customerFullName = "Marvin Quintin"
                        });
                });

            modelBuilder.Entity("Assignment1.Models.Incident", b =>
                {
                    b.Property<int>("incidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateOpened")
                        .HasColumnType("datetime2");

                    b.Property<string>("incidentCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("incidentProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("incidentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("incidentId");

                    b.ToTable("Incident");

                    b.HasData(
                        new
                        {
                            incidentId = 1,
                            dateOpened = new DateTime(2020, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            incidentCustomer = "Kendall Mayte",
                            incidentProduct = "Draft Manager 1.0",
                            incidentTitle = "Could not install"
                        },
                        new
                        {
                            incidentId = 2,
                            dateOpened = new DateTime(2020, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            incidentCustomer = "Gonzoalo Keeton",
                            incidentProduct = "Tournament Master 1.0",
                            incidentTitle = "Could not install"
                        },
                        new
                        {
                            incidentId = 3,
                            dateOpened = new DateTime(2020, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            incidentCustomer = "Ania Irvin",
                            incidentProduct = "League Scheduler Deluxe 1.0",
                            incidentTitle = "Error importing data"
                        },
                        new
                        {
                            incidentId = 4,
                            dateOpened = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            incidentCustomer = "Ania Irvin",
                            incidentProduct = "League Scheduler 1.0",
                            incidentTitle = "Error launching data"
                        });
                });

            modelBuilder.Entity("Assignment1.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("productCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("productPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            productCode = "M2MD6D",
                            productName = "Software Package Vol. 1",
                            productPrice = 4.9900000000000002,
                            releaseDate = new DateTime(2021, 2, 20, 16, 57, 31, 364, DateTimeKind.Local).AddTicks(5949)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
